version: "3.9"
services:
  db:
    image: postgres:17-trixie
    container_name: risk-flux-db
    restart: always
    environment:
      POSTGRES_USER: riskfluxuser
      POSTGRES_PASSWORD: riskfluxpass
      POSTGRES_DB: riskfluxintel
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
